package enums;

/**
 * @author iRevThis
 */
public enum WebSocketSendableMessageType {
    NOT_DONE,
    USER_INFO,
    CHAR_INFO,
    NPC_INFO,
    ABNORMAL_STATUS_UPDATE,
    CHAT_MESSAGE,
    STATUS_UPDATE,
    ETC_STATUS_UPDATE,
    DIE,
    REVIVE,
    PARTY_SMALL_WINDOW_ADD,
    PARTY_SMALL_WINDOW_ALL,
    PARTY_SMALL_WINDOW_DELETE_ALL,
    PARTY_SMALL_WINDOW_DELETE,
    PARTY_SMALL_WINDOW_UPDATE,
    PARTY_SPELLED,
    INVENTORY_UPDATE_DEFAULT,
    INVENTORY_UPDATE,
    CHAR_MOVE_TO_LOCATION,
    VALIDATE_LOCATION,
    TARGET_SELECTED,
    TARGET_UNSELECTED,
    ASSOCIATED_SOCKET,
    TCP_SOCKET_DIE, DELETE_OBJECT, USER_STATS, SHORT_INFO_LIST
}
